name: SCCM

on:
  workflow_dispatch:

jobs:
  get-to-sccm:
    runs-on:
      - self-hosted
      - sccm

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: connect to sccm
        run: |
          Set-Location 'C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin'
          Import-Module .\ConfigurationManager.psd1
          Set-Location SNS:
          Get-CMDevice                    
      - name: run a script
        run: |
          echo "<pre>" >> $GITHUB_STEP_SUMMARY
          ${{ github.workspace }}/samples/CommonFunctions.ps1 >> $GITHUB_STEP_SUMMARY
          echo "</pre>" >> $GITHUB_STEP_SUMMARY
        

